// <auto-generated />
namespace Return.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentClassAssignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentClassAssignment));
        
        string IMigrationMetadata.Id
        {
            get { return "202403201902476_StudentClass-Assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
